### ISSUE TITLE
Recent changes have broken outline sorting

### ISSUE THREAD

**Issue by HopperTech** [kitesi/scoped-sort#10]
The following markdown task list had been sorting correctly until the recent update. 
Now the first lines of each grouping are shifting down one. i.e. `- [x] (a0)` shifts into the `- [ ] (a1)` location, and that line shifts down to 

Note: I have removed my own content of each task, but this process had previously sorted correctly so that I could mark things as done and the next undone task would sort to the top. 

Provider: VS Code Extension
Version: v3.0.0
Options: Format Sections on Save - using the sort options within the comment 

### Initial List ###
```
<!-- { sort-start -r } -->
 
- [x] (a0) 
  - [x] (1)
  - [x] (2) 
    - review [open tasks](searches\open-tasks.code-search)
  - [x] (3) 
  - [x] (4) 
    - [x] 1) 
    - [x] 2) 
    - [x] 3) 
      - comment 1
      - comment 2
      - comment 3
    - [x] 4) 
    - [x] 5) 
      - comment 1
        - comment 1.a
  
- [ ] (a1) 
  - comment 1 
    - comment 1.a
    - comment 2
    - comment 3

- [ ] (z) 
  - [ ] (1) 
    - comment 1
      - comment 1.a
  - [ ] (2) 
    comment 1
    - comment 2
  - [ ] (3) 
  - [ ] (4) 
  - [ ] (5) 
    - comment 1
<!-- { sort-end } -->
```
### Resulting List ###
```
<!-- { sort-start -r } -->
 
  - [x] (1)
  - [x] (2) 
    - review [open tasks](searches\open-tasks.code-search)
  - [x] (3) 
  - [x] (4) 
    - [x] 1) 
    - [x] 2) 
    - [x] 3) 
      - comment 1
      - comment 2
      - comment 3
    - [x] 4) 
    - [x] 5) 
      - comment 1
        - comment 1.a
  
- [x] (a0) 
  - comment 1 
    - comment 1.a
    - comment 2
    - comment 3

- [ ] (a1) 
  - [ ] (1) 
    - comment 1
      - comment 1.a
  - [ ] (2) 
    - comment 2
    comment 1
  - [ ] (3) 
  - [ ] (4) 
  - [ ] (5) 
    - comment 1
- [ ] (z) 
<!-- { sort-end } -->
```

**Comment by testeracc235** [comment]
Could you specify the following: 
- provider (vscode extension, npm, cli, website) you are using
- version number
- options you are using (recursive, markdown, etc..)

Also would be helpful if you contained your text inside of a code block as it currently renders into a markdown checklist, and I can't copy paste.

https://www.markdownguide.org/extended-syntax/#fenced-code-blocks

Example:

```
- [x](a1)
- [ ](a2)
```

**Comment by HopperTech** [comment]
Thanks for clarifying how to format the issue, I have updated my initial comment.

**Comment by sixskys** [comment]
Would I be correct to assume the following output is your desire?:

```text
<!-- { sort-start -r } -->

- [ ] (a1)
  - comment 1
    - comment 1.a
    - comment 2
    - comment 3

- [ ] (z)
  - [ ] (1)
    - comment 1
      - comment 1.a
  - [ ] (2)
    - comment 2
    comment 1
  - [ ] (3)
  - [ ] (4)
  - [ ] (5)
    - comment 1 // line x
- [x] (a0)
  - [x] (1)
  - [x] (2)
    - review [open tasks](searchesopen-tasks.code-search)
  - [x] (3)
  - [x] (4)
    - [x] 1)
    - [x] 2)
    - [x] 3)[src](https://github.com/sixskys/scoped-sort/tree/f1767b0382c9e207600263502b2c345c339a1db2/vscode/src)
      - comment 1
      - comment 2
      - comment 3
    - [x] 4)
    - [x] 5)
      - comment 1
        - comment 1.a
 <!-- { sort-end } -->
```

There is an awkward no blank line after `- [] (z)`'s `- comment 1` (line x), but that would have been the same case in the previous versions, and there is no way to fix that.

I believe the reason for this bug is because on the new line after your sort-start comment, you have a blank line with a single space. 

Highlight the text below and you'll see it:

```
<!-- { sort-start -r } -->
 
```

This tells the program the initial indentation is of length 1, when it should start off with 0.

The reason it worked earlier was because before, the vscode extension searched through the document itself and sorted sort-comments (probably ignoring your empty line with one space). Where as now it just uses the npm's `sortComments()` which has ig a slight different approach.

**SOLUTION**

I believe this should be a pretty easy fix, but currently I'm in the middle of a huge rework of the entire project. I am just about done though, so maybe in like a few days or week (or 2) I'll have a proper fix.

For now you can simply remove the empty space.

**Comment by HopperTech** [comment]
Thank you for the quick response. 
I removed that space, and things sort as they should. I did not realize that was even there.  
Looking forward to the updates when you are able to get to them.
